<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ejercicio;

class EjerciciosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ejercicios = [
            // =============================================
            // PECHO
            // =============================================
            [
                'nombre' => 'Press de banca plano',
                'nombre_alternativo' => 'Bench press',
                'grupos_musculares' => ['pecho', 'triceps', 'hombros'],
                'equipamiento' => ['barra', 'banco plano'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
                'descripcion' => 'Ejercicio compuesto principal para desarrollo del pecho.',
                'instrucciones' => 'Acostado en banco plano, agarrar la barra con agarre medio. Bajar controladamente hasta el pecho y empujar hasta extensión completa.',
            ],
            [
                'nombre' => 'Press de banca inclinado',
                'nombre_alternativo' => 'Incline bench press',
                'grupos_musculares' => ['pecho', 'triceps', 'hombros'],
                'equipamiento' => ['barra', 'banco inclinado'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
                'descripcion' => 'Variante que enfatiza la porción clavicular del pectoral.',
            ],
            [
                'nombre' => 'Press de banca declinado',
                'nombre_alternativo' => 'Decline bench press',
                'grupos_musculares' => ['pecho', 'triceps'],
                'equipamiento' => ['barra', 'banco declinado'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Press con mancuernas plano',
                'nombre_alternativo' => 'Dumbbell bench press',
                'grupos_musculares' => ['pecho', 'triceps', 'hombros'],
                'equipamiento' => ['mancuernas', 'banco plano'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Press con mancuernas inclinado',
                'nombre_alternativo' => 'Incline dumbbell press',
                'grupos_musculares' => ['pecho', 'triceps', 'hombros'],
                'equipamiento' => ['mancuernas', 'banco inclinado'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Aperturas con mancuernas',
                'nombre_alternativo' => 'Dumbbell flyes',
                'grupos_musculares' => ['pecho'],
                'equipamiento' => ['mancuernas', 'banco plano'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Aperturas inclinadas',
                'nombre_alternativo' => 'Incline flyes',
                'grupos_musculares' => ['pecho'],
                'equipamiento' => ['mancuernas', 'banco inclinado'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Cruces en polea alta',
                'nombre_alternativo' => 'Cable crossover high',
                'grupos_musculares' => ['pecho'],
                'equipamiento' => ['poleas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Cruces en polea baja',
                'nombre_alternativo' => 'Cable crossover low',
                'grupos_musculares' => ['pecho'],
                'equipamiento' => ['poleas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Flexiones de brazos',
                'nombre_alternativo' => 'Push ups',
                'grupos_musculares' => ['pecho', 'triceps', 'hombros', 'core'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Fondos en paralelas',
                'nombre_alternativo' => 'Dips',
                'grupos_musculares' => ['pecho', 'triceps', 'hombros'],
                'equipamiento' => ['paralelas'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Pec deck (mariposa)',
                'nombre_alternativo' => 'Pec deck machine',
                'grupos_musculares' => ['pecho'],
                'equipamiento' => ['máquina'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],

            // =============================================
            // ESPALDA
            // =============================================
            [
                'nombre' => 'Dominadas',
                'nombre_alternativo' => 'Pull ups',
                'grupos_musculares' => ['espalda', 'biceps', 'antebrazos'],
                'equipamiento' => ['barra fija'],
                'tipo' => 'fuerza',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Dominadas agarre supino',
                'nombre_alternativo' => 'Chin ups',
                'grupos_musculares' => ['espalda', 'biceps'],
                'equipamiento' => ['barra fija'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Remo con barra',
                'nombre_alternativo' => 'Barbell row',
                'grupos_musculares' => ['espalda', 'biceps', 'core'],
                'equipamiento' => ['barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Remo con mancuerna',
                'nombre_alternativo' => 'Dumbbell row',
                'grupos_musculares' => ['espalda', 'biceps'],
                'equipamiento' => ['mancuerna', 'banco'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Remo en polea baja',
                'nombre_alternativo' => 'Seated cable row',
                'grupos_musculares' => ['espalda', 'biceps'],
                'equipamiento' => ['polea'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Jalón al pecho',
                'nombre_alternativo' => 'Lat pulldown',
                'grupos_musculares' => ['espalda', 'biceps'],
                'equipamiento' => ['polea alta'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Jalón tras nuca',
                'nombre_alternativo' => 'Behind neck pulldown',
                'grupos_musculares' => ['espalda'],
                'equipamiento' => ['polea alta'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Pullover con mancuerna',
                'nombre_alternativo' => 'Dumbbell pullover',
                'grupos_musculares' => ['espalda', 'pecho'],
                'equipamiento' => ['mancuerna', 'banco'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Peso muerto',
                'nombre_alternativo' => 'Deadlift',
                'grupos_musculares' => ['espalda baja', 'gluteos', 'isquiotibiales', 'cuadriceps'],
                'equipamiento' => ['barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Peso muerto rumano',
                'nombre_alternativo' => 'Romanian deadlift',
                'grupos_musculares' => ['isquiotibiales', 'gluteos', 'espalda baja'],
                'equipamiento' => ['barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Hiperextensiones',
                'nombre_alternativo' => 'Back extensions',
                'grupos_musculares' => ['espalda baja', 'gluteos'],
                'equipamiento' => ['banco romano'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Remo en máquina',
                'nombre_alternativo' => 'Machine row',
                'grupos_musculares' => ['espalda', 'biceps'],
                'equipamiento' => ['máquina'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Face pull',
                'nombre_alternativo' => 'Face pull',
                'grupos_musculares' => ['espalda alta', 'hombros posteriores'],
                'equipamiento' => ['polea'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],

            // =============================================
            // HOMBROS
            // =============================================
            [
                'nombre' => 'Press militar',
                'nombre_alternativo' => 'Overhead press',
                'grupos_musculares' => ['hombros', 'triceps'],
                'equipamiento' => ['barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Press con mancuernas sentado',
                'nombre_alternativo' => 'Seated dumbbell press',
                'grupos_musculares' => ['hombros', 'triceps'],
                'equipamiento' => ['mancuernas', 'banco'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Elevaciones laterales',
                'nombre_alternativo' => 'Lateral raises',
                'grupos_musculares' => ['hombros'],
                'equipamiento' => ['mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Elevaciones frontales',
                'nombre_alternativo' => 'Front raises',
                'grupos_musculares' => ['hombros'],
                'equipamiento' => ['mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Pájaros (elevaciones posteriores)',
                'nombre_alternativo' => 'Rear delt flyes',
                'grupos_musculares' => ['hombros posteriores'],
                'equipamiento' => ['mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Remo al mentón',
                'nombre_alternativo' => 'Upright row',
                'grupos_musculares' => ['hombros', 'trapecios'],
                'equipamiento' => ['barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Encogimientos de hombros',
                'nombre_alternativo' => 'Shrugs',
                'grupos_musculares' => ['trapecios'],
                'equipamiento' => ['barra', 'mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Press Arnold',
                'nombre_alternativo' => 'Arnold press',
                'grupos_musculares' => ['hombros'],
                'equipamiento' => ['mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],

            // =============================================
            // BRAZOS - BICEPS
            // =============================================
            [
                'nombre' => 'Curl con barra',
                'nombre_alternativo' => 'Barbell curl',
                'grupos_musculares' => ['biceps'],
                'equipamiento' => ['barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Curl con mancuernas',
                'nombre_alternativo' => 'Dumbbell curl',
                'grupos_musculares' => ['biceps'],
                'equipamiento' => ['mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Curl martillo',
                'nombre_alternativo' => 'Hammer curl',
                'grupos_musculares' => ['biceps', 'antebrazos'],
                'equipamiento' => ['mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Curl concentrado',
                'nombre_alternativo' => 'Concentration curl',
                'grupos_musculares' => ['biceps'],
                'equipamiento' => ['mancuerna'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Curl en banco Scott',
                'nombre_alternativo' => 'Preacher curl',
                'grupos_musculares' => ['biceps'],
                'equipamiento' => ['barra EZ', 'banco scott'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Curl en polea',
                'nombre_alternativo' => 'Cable curl',
                'grupos_musculares' => ['biceps'],
                'equipamiento' => ['polea'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Curl con barra Z',
                'nombre_alternativo' => 'EZ bar curl',
                'grupos_musculares' => ['biceps'],
                'equipamiento' => ['barra EZ'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],

            // =============================================
            // BRAZOS - TRICEPS
            // =============================================
            [
                'nombre' => 'Press francés',
                'nombre_alternativo' => 'Skull crushers',
                'grupos_musculares' => ['triceps'],
                'equipamiento' => ['barra EZ', 'banco'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Extensiones en polea',
                'nombre_alternativo' => 'Tricep pushdown',
                'grupos_musculares' => ['triceps'],
                'equipamiento' => ['polea'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Extensiones con soga',
                'nombre_alternativo' => 'Rope pushdown',
                'grupos_musculares' => ['triceps'],
                'equipamiento' => ['polea', 'soga'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Patada de tríceps',
                'nombre_alternativo' => 'Tricep kickback',
                'grupos_musculares' => ['triceps'],
                'equipamiento' => ['mancuerna'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Extensiones sobre cabeza',
                'nombre_alternativo' => 'Overhead tricep extension',
                'grupos_musculares' => ['triceps'],
                'equipamiento' => ['mancuerna'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Press cerrado',
                'nombre_alternativo' => 'Close grip bench press',
                'grupos_musculares' => ['triceps', 'pecho'],
                'equipamiento' => ['barra', 'banco'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Fondos en banco',
                'nombre_alternativo' => 'Bench dips',
                'grupos_musculares' => ['triceps'],
                'equipamiento' => ['banco'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],

            // =============================================
            // PIERNAS - CUADRICEPS
            // =============================================
            [
                'nombre' => 'Sentadilla con barra',
                'nombre_alternativo' => 'Barbell squat',
                'grupos_musculares' => ['cuadriceps', 'gluteos', 'isquiotibiales'],
                'equipamiento' => ['barra', 'rack'],
                'tipo' => 'fuerza',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Sentadilla frontal',
                'nombre_alternativo' => 'Front squat',
                'grupos_musculares' => ['cuadriceps', 'core'],
                'equipamiento' => ['barra', 'rack'],
                'tipo' => 'fuerza',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Sentadilla goblet',
                'nombre_alternativo' => 'Goblet squat',
                'grupos_musculares' => ['cuadriceps', 'gluteos'],
                'equipamiento' => ['mancuerna', 'kettlebell'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Prensa de piernas',
                'nombre_alternativo' => 'Leg press',
                'grupos_musculares' => ['cuadriceps', 'gluteos'],
                'equipamiento' => ['máquina prensa'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Extensiones de cuádriceps',
                'nombre_alternativo' => 'Leg extension',
                'grupos_musculares' => ['cuadriceps'],
                'equipamiento' => ['máquina'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Hack squat',
                'nombre_alternativo' => 'Hack squat',
                'grupos_musculares' => ['cuadriceps', 'gluteos'],
                'equipamiento' => ['máquina hack'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Sentadilla búlgara',
                'nombre_alternativo' => 'Bulgarian split squat',
                'grupos_musculares' => ['cuadriceps', 'gluteos'],
                'equipamiento' => ['mancuernas', 'banco'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Estocadas (zancadas)',
                'nombre_alternativo' => 'Lunges',
                'grupos_musculares' => ['cuadriceps', 'gluteos'],
                'equipamiento' => ['mancuernas', 'barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Estocadas caminando',
                'nombre_alternativo' => 'Walking lunges',
                'grupos_musculares' => ['cuadriceps', 'gluteos'],
                'equipamiento' => ['mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Sentadilla sissy',
                'nombre_alternativo' => 'Sissy squat',
                'grupos_musculares' => ['cuadriceps'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'avanzado',
            ],

            // =============================================
            // PIERNAS - ISQUIOTIBIALES
            // =============================================
            [
                'nombre' => 'Curl femoral acostado',
                'nombre_alternativo' => 'Lying leg curl',
                'grupos_musculares' => ['isquiotibiales'],
                'equipamiento' => ['máquina'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Curl femoral sentado',
                'nombre_alternativo' => 'Seated leg curl',
                'grupos_musculares' => ['isquiotibiales'],
                'equipamiento' => ['máquina'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Buenos días',
                'nombre_alternativo' => 'Good mornings',
                'grupos_musculares' => ['isquiotibiales', 'espalda baja', 'gluteos'],
                'equipamiento' => ['barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Curl nórdico',
                'nombre_alternativo' => 'Nordic curl',
                'grupos_musculares' => ['isquiotibiales'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'avanzado',
            ],

            // =============================================
            // PIERNAS - GLUTEOS
            // =============================================
            [
                'nombre' => 'Hip thrust',
                'nombre_alternativo' => 'Hip thrust',
                'grupos_musculares' => ['gluteos', 'isquiotibiales'],
                'equipamiento' => ['barra', 'banco'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Puente de glúteos',
                'nombre_alternativo' => 'Glute bridge',
                'grupos_musculares' => ['gluteos'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Patada de glúteo en polea',
                'nombre_alternativo' => 'Cable kickback',
                'grupos_musculares' => ['gluteos'],
                'equipamiento' => ['polea'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Abducción de cadera',
                'nombre_alternativo' => 'Hip abduction',
                'grupos_musculares' => ['gluteos', 'abductores'],
                'equipamiento' => ['máquina'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Step up',
                'nombre_alternativo' => 'Step up',
                'grupos_musculares' => ['gluteos', 'cuadriceps'],
                'equipamiento' => ['cajón', 'mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],

            // =============================================
            // PIERNAS - PANTORRILLAS
            // =============================================
            [
                'nombre' => 'Elevación de talones de pie',
                'nombre_alternativo' => 'Standing calf raise',
                'grupos_musculares' => ['pantorrillas'],
                'equipamiento' => ['máquina', 'barra'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Elevación de talones sentado',
                'nombre_alternativo' => 'Seated calf raise',
                'grupos_musculares' => ['pantorrillas'],
                'equipamiento' => ['máquina'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Elevación de talones en prensa',
                'nombre_alternativo' => 'Leg press calf raise',
                'grupos_musculares' => ['pantorrillas'],
                'equipamiento' => ['prensa'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],

            // =============================================
            // CORE / ABDOMINALES
            // =============================================
            [
                'nombre' => 'Plancha frontal',
                'nombre_alternativo' => 'Plank',
                'grupos_musculares' => ['core', 'abdominales'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Plancha lateral',
                'nombre_alternativo' => 'Side plank',
                'grupos_musculares' => ['core', 'oblicuos'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Crunch abdominal',
                'nombre_alternativo' => 'Crunch',
                'grupos_musculares' => ['abdominales'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Crunch en polea',
                'nombre_alternativo' => 'Cable crunch',
                'grupos_musculares' => ['abdominales'],
                'equipamiento' => ['polea'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Elevación de piernas colgado',
                'nombre_alternativo' => 'Hanging leg raise',
                'grupos_musculares' => ['abdominales', 'core'],
                'equipamiento' => ['barra fija'],
                'tipo' => 'fuerza',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Elevación de piernas acostado',
                'nombre_alternativo' => 'Lying leg raise',
                'grupos_musculares' => ['abdominales'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Rueda abdominal',
                'nombre_alternativo' => 'Ab wheel rollout',
                'grupos_musculares' => ['abdominales', 'core'],
                'equipamiento' => ['rueda abdominal'],
                'tipo' => 'fuerza',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Bicicleta',
                'nombre_alternativo' => 'Bicycle crunch',
                'grupos_musculares' => ['abdominales', 'oblicuos'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Russian twist',
                'nombre_alternativo' => 'Russian twist',
                'grupos_musculares' => ['oblicuos', 'core'],
                'equipamiento' => ['peso corporal', 'pelota medicinal'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Mountain climbers',
                'nombre_alternativo' => 'Mountain climbers',
                'grupos_musculares' => ['core', 'abdominales'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'cardio',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Dead bug',
                'nombre_alternativo' => 'Dead bug',
                'grupos_musculares' => ['core', 'abdominales'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Bird dog',
                'nombre_alternativo' => 'Bird dog',
                'grupos_musculares' => ['core', 'espalda baja'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],

            // =============================================
            // ANTEBRAZOS
            // =============================================
            [
                'nombre' => 'Curl de muñeca',
                'nombre_alternativo' => 'Wrist curl',
                'grupos_musculares' => ['antebrazos'],
                'equipamiento' => ['barra', 'mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Curl de muñeca invertido',
                'nombre_alternativo' => 'Reverse wrist curl',
                'grupos_musculares' => ['antebrazos'],
                'equipamiento' => ['barra', 'mancuernas'],
                'tipo' => 'fuerza',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Farmer walk',
                'nombre_alternativo' => 'Farmer walk',
                'grupos_musculares' => ['antebrazos', 'trapecios', 'core'],
                'equipamiento' => ['mancuernas', 'kettlebells'],
                'tipo' => 'fuerza',
                'dificultad' => 'intermedio',
            ],

            // =============================================
            // CARDIO
            // =============================================
            [
                'nombre' => 'Cinta de correr',
                'nombre_alternativo' => 'Treadmill',
                'grupos_musculares' => ['cardio', 'piernas'],
                'equipamiento' => ['cinta'],
                'tipo' => 'cardio',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Bicicleta estática',
                'nombre_alternativo' => 'Stationary bike',
                'grupos_musculares' => ['cardio', 'piernas'],
                'equipamiento' => ['bicicleta'],
                'tipo' => 'cardio',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Elíptica',
                'nombre_alternativo' => 'Elliptical',
                'grupos_musculares' => ['cardio', 'piernas'],
                'equipamiento' => ['elíptica'],
                'tipo' => 'cardio',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Remo ergómetro',
                'nombre_alternativo' => 'Rowing machine',
                'grupos_musculares' => ['cardio', 'espalda', 'piernas'],
                'equipamiento' => ['remo'],
                'tipo' => 'cardio',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Saltar la soga',
                'nombre_alternativo' => 'Jump rope',
                'grupos_musculares' => ['cardio', 'pantorrillas'],
                'equipamiento' => ['soga'],
                'tipo' => 'cardio',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Burpees',
                'nombre_alternativo' => 'Burpees',
                'grupos_musculares' => ['cardio', 'cuerpo completo'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'cardio',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Jumping jacks',
                'nombre_alternativo' => 'Jumping jacks',
                'grupos_musculares' => ['cardio'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'cardio',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Box jumps',
                'nombre_alternativo' => 'Box jumps',
                'grupos_musculares' => ['piernas', 'gluteos'],
                'equipamiento' => ['cajón'],
                'tipo' => 'potencia',
                'dificultad' => 'intermedio',
            ],

            // =============================================
            // POTENCIA / OLÍMPICOS
            // =============================================
            [
                'nombre' => 'Clean (cargada)',
                'nombre_alternativo' => 'Power clean',
                'grupos_musculares' => ['cuerpo completo'],
                'equipamiento' => ['barra'],
                'tipo' => 'potencia',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Snatch (arrancada)',
                'nombre_alternativo' => 'Snatch',
                'grupos_musculares' => ['cuerpo completo'],
                'equipamiento' => ['barra'],
                'tipo' => 'potencia',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Clean and jerk',
                'nombre_alternativo' => 'Clean and jerk',
                'grupos_musculares' => ['cuerpo completo'],
                'equipamiento' => ['barra'],
                'tipo' => 'potencia',
                'dificultad' => 'avanzado',
            ],
            [
                'nombre' => 'Kettlebell swing',
                'nombre_alternativo' => 'Kettlebell swing',
                'grupos_musculares' => ['gluteos', 'isquiotibiales', 'core'],
                'equipamiento' => ['kettlebell'],
                'tipo' => 'potencia',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Thruster',
                'nombre_alternativo' => 'Thruster',
                'grupos_musculares' => ['piernas', 'hombros'],
                'equipamiento' => ['barra', 'mancuernas'],
                'tipo' => 'potencia',
                'dificultad' => 'intermedio',
            ],

            // =============================================
            // FLEXIBILIDAD / MOVILIDAD
            // =============================================
            [
                'nombre' => 'Estiramiento de isquiotibiales',
                'nombre_alternativo' => 'Hamstring stretch',
                'grupos_musculares' => ['isquiotibiales'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Estiramiento de cuádriceps',
                'nombre_alternativo' => 'Quad stretch',
                'grupos_musculares' => ['cuadriceps'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Estiramiento de pecho',
                'nombre_alternativo' => 'Chest stretch',
                'grupos_musculares' => ['pecho'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Estiramiento de hombros',
                'nombre_alternativo' => 'Shoulder stretch',
                'grupos_musculares' => ['hombros'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Foam rolling (automasaje)',
                'nombre_alternativo' => 'Foam rolling',
                'grupos_musculares' => ['cuerpo completo'],
                'equipamiento' => ['foam roller'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Postura del niño (yoga)',
                'nombre_alternativo' => 'Child\'s pose',
                'grupos_musculares' => ['espalda', 'hombros'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Perro boca abajo (yoga)',
                'nombre_alternativo' => 'Downward dog',
                'grupos_musculares' => ['isquiotibiales', 'pantorrillas', 'espalda'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'principiante',
            ],
            [
                'nombre' => 'Estiramiento de cadera (90/90)',
                'nombre_alternativo' => '90/90 hip stretch',
                'grupos_musculares' => ['cadera', 'gluteos'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'intermedio',
            ],
            [
                'nombre' => 'Cat-cow (gato-vaca)',
                'nombre_alternativo' => 'Cat-cow stretch',
                'grupos_musculares' => ['espalda', 'core'],
                'equipamiento' => ['peso corporal'],
                'tipo' => 'flexibilidad',
                'dificultad' => 'principiante',
            ],
        ];

        foreach ($ejercicios as $ejercicio) {
            Ejercicio::create([
                'nombre' => $ejercicio['nombre'],
                'nombre_alternativo' => $ejercicio['nombre_alternativo'] ?? null,
                'descripcion' => $ejercicio['descripcion'] ?? null,
                'instrucciones' => $ejercicio['instrucciones'] ?? null,
                'grupos_musculares' => $ejercicio['grupos_musculares'],
                'equipamiento' => $ejercicio['equipamiento'],
                'tipo' => $ejercicio['tipo'],
                'dificultad' => $ejercicio['dificultad'],
                'es_personalizado' => false,
                'creado_por' => null,
            ]);
        }

        $this->command->info('Se crearon ' . count($ejercicios) . ' ejercicios.');
    }
}
